var first_name = "Zac";
var last_name = "yang";
var full_name = first_name.concat(last_name);
console.log(full_name);
var a = 200;
var b = 300;
console.log(a+b);
console.log(a-b);
console.log(a*b);
console.log(a/b);
